// src/utils/auditEvents.js

/*
 * Single source of truth for audit event names and their severities.
 * Both the AuditLog model (enum validation) and the audit logger import
 * from here so the lists can never drift apart.
 */

export const AUDIT_EVENTS = Object.freeze({
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILED: "LOGIN_FAILED",

  LOGOUT: "LOGOUT",
  LOGOUT_ALL: "LOGOUT_ALL",

  SESSION_CREATED: "SESSION_CREATED",
  SESSION_REVOKED: "SESSION_REVOKED",
  SESSION_LIMIT_EXCEEDED: "SESSION_LIMIT_EXCEEDED",

  TOKEN_REFRESHED: "TOKEN_REFRESHED",
  TOKEN_REPLAY_DETECTED: "TOKEN_REPLAY_DETECTED",

  PASSWORD_CHANGED: "PASSWORD_CHANGED",
  PASSWORD_RESET_REQUESTED: "PASSWORD_RESET_REQUESTED",
  PASSWORD_RESET: "PASSWORD_RESET",

  PROFILE_UPDATED: "PROFILE_UPDATED",

  OTP_SENT: "OTP_SENT",
  OTP_VERIFIED: "OTP_VERIFIED",
  OTP_FAILED: "OTP_FAILED",
  STEP_UP_REQUIRED: "STEP_UP_REQUIRED",
  STEP_UP_PASSED: "STEP_UP_PASSED",
  DEVICE_TRUSTED: "DEVICE_TRUSTED",

  CSRF_FAILURE: "CSRF_FAILURE",
  RATE_LIMIT_TRIGGERED: "RATE_LIMIT_TRIGGERED",

  NEW_DEVICE_DETECTED: "NEW_DEVICE_DETECTED",
  SUSPICIOUS_IP_DETECTED: "SUSPICIOUS_IP_DETECTED",
  USER_DELETED: "USER_DELETED",
  USER_ROLE_CHANGED: "USER_ROLE_CHANGED",
  SYSTEM_ERROR: "SYSTEM_ERROR",
  AUDIT_INTEGRITY_CHECKED: "AUDIT_INTEGRITY_CHECKED",
});

export const EVENT_SEVERITY = Object.freeze({
  LOGIN_SUCCESS: "INFO",
  LOGIN_FAILED: "WARN",

  LOGOUT: "INFO",
  LOGOUT_ALL: "INFO",

  SESSION_CREATED: "INFO",
  SESSION_REVOKED: "WARN",
  SESSION_LIMIT_EXCEEDED: "WARN",

  TOKEN_REFRESHED: "INFO",
  TOKEN_REPLAY_DETECTED: "CRITICAL",

  PASSWORD_CHANGED: "WARN",
  PASSWORD_RESET_REQUESTED: "WARN",
  PASSWORD_RESET: "CRITICAL",

  PROFILE_UPDATED: "INFO",

  OTP_SENT: "INFO",
  OTP_VERIFIED: "INFO",
  OTP_FAILED: "WARN",
  STEP_UP_REQUIRED: "WARN",
  STEP_UP_PASSED: "INFO",
  DEVICE_TRUSTED: "INFO",

  CSRF_FAILURE: "WARN",
  RATE_LIMIT_TRIGGERED: "ERROR",

  NEW_DEVICE_DETECTED: "WARN",
  SUSPICIOUS_IP_DETECTED: "HIGH",
  USER_DELETED: "CRITICAL",
  USER_ROLE_CHANGED: "CRITICAL",
  SYSTEM_ERROR: "CRITICAL",
  AUDIT_INTEGRITY_CHECKED: "INFO",
});
